### ISSUE TITLE
Error when installing package

### ISSUE THREAD

**Issue by saeidalidadi** [google/boardgame.io#10]
I got this installation error.

## command
 `npm install --save boardgame.io`

## log
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! boardgame.io@0.11.3 postinstall: `ln -s ../packages node_modules/boardgame.io`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the boardgame.io@0.11.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Env

node.js 8.9.3
Linux Ubuntu 16.0.4

**Comment by saeidalidadi** [comment]
I fixed this issue, but I could not run tests and I will report new one for that.

**Comment by abramz** [comment]
@saeidalidadi how? would be nice for people searching (like me)

**Comment by abramz** [comment]
can you bump the npm version @nicolodavis, this is still happening when trying to install

**Comment by nicolodavis** [comment]
Done. Can you check now?

**Comment by abramz** [comment]
It works now, thanks, @nicolodavis! this is really cool btw

**Comment by nicolodavis** [comment]
Lots of work to be done before it's ready for v1.0, but we'll get there!
